AWSTemplateFormatVersion: "2010-09-09"
Description: "ACTIVE backend ($0.105/hour): https://github.com/paulmossman/easy-aws-privacy-vpn/blob/main/README.md"

Parameters:

  VpcId:
    Type: String
  ClientVpnEndpointId:
    Type: String
  SubnetId:
    Type: String

Resources:

  TargetNetworkAssociation:
    Type: "AWS::EC2::ClientVpnTargetNetworkAssociation"
    Properties:
      ClientVpnEndpointId: !Ref ClientVpnEndpointId
      SubnetId: !Ref SubnetId

  ClientVpnRouteToInternet:
    Type: "AWS::EC2::ClientVpnRoute"
    Properties:
      ClientVpnEndpointId: !Ref ClientVpnEndpointId
      Description: "Internet Route"
      DestinationCidrBlock: "0.0.0.0/0"
      TargetVpcSubnetId: !Ref SubnetId
    DependsOn: TargetNetworkAssociation
